spring.application.name=sherlock
server.port=8080

spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=250MB

sherlock.base-directory=../../data
sherlock.python-command=python3
sherlock.python-script-path=
sherlock.process-argument=--case-id

sherlock.neo4j.uri=bolt://localhost:7687
sherlock.neo4j.username=neo4j
sherlock.neo4j.password=password
sherlock.neo4j.database=neo4j
sherlock.neo4j.enabled=true

logging.level.com.sherlock=INFO
